theme = "gruvbox_dark_hard"

[editor]
bufferline = "always"
true-color = true
color-modes = true
rulers = [80, 120]
auto-save = true
line-number = "absolute"
auto-pairs = false
cursorline = true
auto-format = true
insert-final-newline = false

[editor.lsp]
enable = true
display-messages = true
snippets = false

[editor.whitespace.render]
tab = "all"
nbsp = "all"
newline = "all"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
space.F = "file_picker_in_current_buffer_directory"
space.X = ":reset-diff-change"

"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

space.c = "toggle_comments"
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
del = "delete_char_forward"
S-up = ["select_mode", "extend_visual_line_up"]
S-down = ["select_mode", "extend_visual_line_down"]
S-left = ["select_mode", "extend_char_left"]
S-right = ["select_mode", "extend_char_right"]

[keys.insert]
C-c = "normal_mode"
C-right = ["move_next_word_end", "move_char_right", "collapse_selection"]
C-left = ["move_prev_word_start", "collapse_selection"]
S-up = ["select_mode", "extend_visual_line_up"]
S-down = ["select_mode", "extend_visual_line_down"]
S-left = ["select_mode", "extend_char_left"]
S-right = ["select_mode", "extend_char_right"]

[keys.select]
space.F = "file_picker_in_current_buffer_directory"
S-up = ["select_mode", "extend_visual_line_up"]
S-down = ["select_mode", "extend_visual_line_down"]
S-left = "extend_char_left"
S-right = "extend_char_right"
