theme = "gruvbox_dark_hard"

[editor]
true-color = true
color-modes = true
rulers = [80, 120]
auto-save = true
line-number = "absolute"
auto-pairs = false
cursorline = true
auto-format = false

[editor.lsp]
enable = true
display-messages = true
snippets = false

[editor.whitespace.render]
tab = "all"
nbsp = "all"
newline = "all"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
#"%" = "match_brackets"
# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

D = [ "extend_to_line_end", "change_selection"]
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]

del = "delete_char_forward"
0 = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"

space.c = "toggle_comments"
C-n = "completion"
C-v = ":clipboard-paste-before"

esc = ["keep_primary_selection"]

[keys.insert]
C-v = ":clipboard-paste-before"
C-c = ["keep_primary_selection", "normal_mode"]

[keys.select]
"^" = "extend_to_line_start"
"$" = "extend_to_line_end"

C-v = ":clipboard-paste-replace"
C-c = "yank_to_clipboard"

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
#u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
#U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
