theme = "mytheme"

[editor]
bufferline = "never"
true-color = true
color-modes = true
#rulers = [80, 120]
auto-save = true
line-number = "absolute"
cursorline = true
auto-format = true
insert-final-newline = true
auto-completion = false

[editor.smart-tab]
enable = false

[editor.lsp]
enable = true
display-messages = true
snippets = false

[editor.whitespace.render]
tab = "all"
nbsp = "all"
newline = "all"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "read-only-indicator"]
center = ["register"]
right = ["diagnostics", "spacer", "version-control", "spacer", "separator", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "separator", "file-type"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
space.F = "file_picker_in_current_buffer_directory"
space.X = ":reset-diff-change"

"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

C-up = "copy_selection_on_prev_line"
C-down = "copy_selection_on_next_line"
esc = "keep_primary_selection"

C-right = "move_next_word_start"
C-left = "move_prev_word_end"
del = "delete_char_forward"
S-up = ["select_mode", "extend_visual_line_up"]
S-down = ["select_mode", "extend_visual_line_down"]
S-left = ["select_mode", "extend_char_left"]
S-right = ["select_mode", "extend_char_right"]

space.B = ":run-shell-command $HOME/.config/helix/zellij-helix-blame.sh"

[keys.insert]
C-up = "copy_selection_on_prev_line"
C-down = "copy_selection_on_next_line"
esc = ["keep_primary_selection", "normal_mode"]
C-c = ["keep_primary_selection", "normal_mode"]

C-right = ["move_next_word_end", "move_char_right", "collapse_selection"]
C-left = ["move_prev_word_start", "collapse_selection"]
S-up = ["select_mode", "extend_visual_line_up"]
S-down = ["select_mode", "extend_visual_line_down"]
S-left = ["select_mode", "extend_char_left"]
S-right = ["select_mode", "extend_char_right"]

[keys.select]
space.F = "file_picker_in_current_buffer_directory"
S-up = ["select_mode", "extend_visual_line_up"]
S-down = ["select_mode", "extend_visual_line_down"]
S-left = "extend_char_left"
S-right = "extend_char_right"
C-up = "copy_selection_on_prev_line"
C-down = "copy_selection_on_next_line"
