theme = "gruvbox_dark_hard"

[editor]
bufferline = "always"
true-color = true
color-modes = true
rulers = [80, 120]
auto-save = true
line-number = "absolute"
auto-pairs = false
cursorline = true
auto-format = true
insert-final-newline = false

[editor.lsp]
enable = true
display-messages = true
snippets = false

[editor.whitespace.render]
tab = "all"
nbsp = "all"
newline = "all"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

space.c = "toggle_comments"
C-n = "completion"

[keys.insert]
C-n = "completion"

[keys.select]
